#!/bin/bash
CASTS=$HOME/workspace/termcast/casts
CURRENT="$CASTS/current"

mkdir -p $CASTS

touch $CURRENT
ttyrec -a "$CURRENT" -e "/usr/bin/screen -c screenrc"
killall telnet

if [ $# -eq 1 ]
then
    ARCHIVE="$CASTS/$1"
else
    ARCHIVE="$CASTS/$(date +%F-%T).ttyrec"
fi

mv $CURRENT $ARCHIVE
echo "Saved termcast (to $ARCHIVE)."
